# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://www.hypertesto.me/"
defaultContentLanguage = "it"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[mediaTypes."application/atom+xml"]
suffixes = [ "atom" ]

[outputFormats.atom]
name = "ATOM"
mediaType = "application/atom+xml"
baseName = "feed"
isPlainText = false


[outputs]
  home = ["HTML", "RSS", "ATOM"]
  section = ["HTML", "RSS", "ATOM"]

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
