languageCode = "en"
languageName = "English"
title = "HyperTesto"
weight = 1
#contentDir = "content/english"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.jpg"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]

  name = "HyperTesto"
  image = "img/avatar_rounded.png"
  headline = "Always coding, always debugging. I thrive in chaos and chaos loves me.</br>But I guarantee I can fix any computer with a hug."
  bio = "Hey, i'm the same guy from the homepage. Incredible, isn't it?"
  links = [
    { github = "https://github.com/HyperTesto" },
    { mastodon = "https://mastodon.uno/@hypertesto" },
    { threads = "https://www.threads.net/@hypertesto" },
    { x-twitter = "https://twitter.com/hypertesto" },
    { linkedin = "https://linkedin.com/in/enricotestori" },
    { telegram = "https://t.me/hypertesto_me" },
    { bmc = "https://www.buymeacoffee.com/hypertesto" },
    { ko-fi = "https://ko-fi.com/hypertesto" },
    { email = "mailto:hello@hypertesto.me" },
    { rss = "/index.xml" }
  ]
