languageCode = "it"
languageName = "Italiano"
title = "HyperTesto"
weight = 1
#contentDir = "content/italian"

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  # logo = "img/logo.jpg"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[author]

  name = "HyperTesto"
  image = "img/avatar_rounded.png"
  headline = "Always coding, always debugging. I thrive in chaos and chaos loves me.</br>But I guarantee I can fix any computer with a hug."
  bio = "Ehi, sono la stessa persona dell'homepage, incredibile vero?"
  links = [
    { github = "https://github.com/HyperTesto" },
    { mastodon = "https://mastodon.uno/@hypertesto" },
    { threads = "https://www.threads.net/@hypertesto" },
    { x-twitter = "https://twitter.com/hypertesto" },
    { linkedin = "https://linkedin.com/in/enricotestori" },
    { telegram = "https://t.me/hypertesto_me" },
    { bmc = "https://www.buymeacoffee.com/hypertesto" },
    { ko-fi = "https://ko-fi.com/hypertesto" },
    { email = "mailto:hello@hypertesto.me" },
    { rss = "/index.xml" }
  ]