[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 30

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[footer]]
  name = "Sitemap"
  url = "/sitemap.xml"
  weight = 40

[[footer]]
  name = "Feed (IT)"
  url = "/index.xml"
  weight = 50
  [footer.params]
    icon = "rss"

[[footer]]
  name = "Feed (EN)"
  url = "/en/index.xml"
  weight = 51
  [footer.params]
    icon = "rss"

[[footer]]
  name = "Repo"
  url = "https://github.com/HyperTesto/hypertesto.me"
  weight = 60
  [footer.params]
    icon = "github"

[[footer]]
name = "Stats"
url = "https://plausible.io/hypertesto.me"
weight = 70
  [footer.params]
    icon = "chart-simple-solid"
