baseURL = "https://www.hypertesto.me"
title = "Enrico Testori"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "it"

[params.info]
description = "Se una cosa sembra troppo semplice, si fa sempre a tempo a renderla più complicata!"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "HyperTesto"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Monday, January 2, 2006"
listDateFormat = "02/01/2006"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#a1855b"

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "hypertesto"

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = "info@hypertesto.me"
facebook = "enrico.testori.12"
github = "HyperTesto"
instagram = "hypertesto"
linkedin = "enricotestori"
twitter = "hypertesto"

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","social_menu","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.social.config]
platforms = ["github","linkedin","facebook","twitter","instagram","email"]

[sidebar_menu]
title = "sidebar"                            # default: ""
mirror = "sidebar"                           # default: ""

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.sidebar]]
name = "» Chiuso in casa"
identifier = "chiuso-in-casa"
url = "/chiuso-in-casa"

[[menu.sidebar]]
name = "» Guida galattica per hughisti"
identifier = "ggph"
url = "/ggph"

[[menu.main]]
name = "Home"
weight = -1000
identifier = "home"
url = "/"

[[menu.main]]
name = "Repo"
weight = 100
identifier = "repository"
url = "https://github.com/HyperTesto/hypertesto.me"

[[menu.main]]
name = "Feed"
weight = 1000
identifier = "feed"
url = "/index.xml"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.it]
lang = "it"
languageName = "Italian"
weight = 1

[params.comments]
enable = true

[params.comments.staticman]
enable = true
apiEndpoint = "https://hyper-staticman.herokuapp.com/v2/entry"
maxDepth = 2
username = "HyperTesto"
repository = "hypertesto.me"

#[params.comments.staticman.github]
#branch = "master"
