[context.production.environment]
  HUGO_VERSION = "0.62.2"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Content-Security-Policy = '''
        default-src https: 'unsafe-inline';
        object-src 'none'; base-uri 'none';
        block-all-mixed-content;
        font-src 'self' 'https://fonts.googleapis.com';
        style-src 'self' 'https://fonts.googleapis.com';'''

    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"

    Access-Control-Allow-Origin = "https://stats.hypertesto.me"

    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
