[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.22.x"
  TZ = "UTC +2"

[context.production.environment]
  HUGO_VERSION = "0.125.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.staging.environment]
  HUGO_VERSION = "0.125.5"
  HUGO_ENV = "staging"
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "public"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    objectSrc = "'none'"
    fontSrc = "'self'"
    styleSrc = "'self' 'unsafe-hashes'"
    scriptSrc = "'self' 'unsafe-hashes' 'unsafe-inline' remark42.hypertesto.me"
    imgSrc = "'self' https:"
    mediaSrc = "'self' https:"
    frameSrc = "youtube.com www.youtube.com www.youtube-nocookie.com remark42.hypertesto.me"
    childSrc = "'none'"
    frameAncestors = "'none'"
    formAction = "'self'"
    connect-src = "remark42.hypertesto.me 'self'"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"

    Access-Control-Allow-Origin = "https://plausible.io"

    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

    Permissions-Policy = "interest-cohort=()"


# Redirects for plausible
[[redirects]]
  from = "/js/plausible.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202
  force = true

# Redirects for Hatsu
[[redirects]]
  from = "/.well-known/host-meta*"
  to = "https://thinkcentre.tail4162e7.ts.net/.well-known/host-meta:splat"
  status = 307
[[redirects]]
  from = "/.well-known/nodeinfo*"
  to = "https://thinkcentre.tail4162e7.ts.net/.well-known/nodeinfo"
  status = 307
[[redirects]]
  from = "/.well-known/webfinger*"
  to = "https://thinkcentre.tail4162e7.ts.net/.well-known/webfinger"
  status = 307

# Headers for atom feed
[[headers]]
  for = "atom.*"
  [headers.values]
    Content-Type = "application/atom+xml; charset=UTF-8"
[[headers]]
  for = "*.atom"
  [headers.values]
    Content-Type = "application/atom+xml; charset=UTF-8"