[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "UTC +2"

[context.production.environment]
  HUGO_VERSION = "0.110.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.staging.environment]
  HUGO_VERSION = "0.110.0"
  HUGO_ENV = "staging"
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "public"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    objectSrc = "'none'"
    fontSrc = "'self'"
    styleSrc = "'self' 'unsafe-hashes'"
    scriptSrc = "'self' 'unsafe-hashes' talk.hyvor.com"
    imgSrc = "'self' https:"
    mediaSrc = "'self' https:"
    frameSrc = "youtube.com www.youtube.com talk.hyvor.com"
    childSrc = "'none'"
    frameAncestors = "'none'"
    formAction = "'self'"
    connect-src = "talk.hyvor.com soketi.hyvor.com 'self'"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"

    Access-Control-Allow-Origin = "https://plausible.io"

    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

    Permissions-Policy = "interest-cohort=()"


# Redirects for plausible
[[redirects]]
  from = "/js/plausible.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202
  force = true
