[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.74.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.74.3"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Content-Security-Policy = '''
        default-src 'none';
        object-src 'none';
        base-uri 'self';
        block-all-mixed-content;
        font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
        style-src 'self' 'unsafe-inline' https://www.gstatic.com https://fonts.googleapis.com *.cloudfront.net;
        script-src 'strict-dynamic' 'self' https://plausible.io https://www.gstatic.com https://www.google.com *.cloudfront.net;
        img-src: https:;
        frame-src https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/;
        child-src 'none';
        form-action 'self' https://hyper-staticman.herokuapp.com/v2/entry;
        frame-ancestors 'none';
        '''

    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"

    Access-Control-Allow-Origin = "https://plausible.io"

    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

    Permissions-Policy = "interest-cohort=()"

# Redirects for plausible
[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202
  force = true
